version: "3.8"

services:
  db:
    image: mysql:5.8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: blog_db
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: Akanksha@123
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3012:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./blogs
    container_name: django_backend
    restart: always
    depends_on:
      - db
    environment:
      - DB_NAME=blog_db
      - DB_USER=blog_user
      - DB_PASSWORD=Akanksha@123
      - DB_HOST=db  
    ports:
      - "8005:8005"
    volumes:
      - ./blogs:/app

  frontend:
    build: ./blog-frontend
    container_name: react_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5005:5005"
    environment:
      - CHOKIDAR_USEPOLLING=true  
    volumes:
      - ./blog-frontend:/app
      - /app/node_modules  

volumes:
  mysql_data:

